version: '3.7'

services:
  backend:
    build: ./api
    container_name: trade_backend
    working_dir: /app
    command: ["/bin/sh", "django_setup.sh"]
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app/
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings.development
  db:
    image: "mysql:5.7"
    container_name: trade_mysql
    ports:
        - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .db_env
  client:
    build: ./client
    container_name: trade_client
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/
      - node-modules:/app/node_modules
    env_file:
      - .client_env
    depends_on:
      - backend

volumes:
  node-modules:
