# Generated by Django 2.2.10 on 2020-02-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string_id', models.CharField(db_index=True, editable=False, max_length=9, unique=True)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_trades', to='trades.Currency')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_trades', to='trades.Currency')),
            ],
            options={
                'db_table': 'trades',
            },
        ),
    ]
