# Generated by Django 2.2.10 on 2020-02-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_added_trade_and_currency_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': 'trade', 'verbose_name_plural': 'trades'},
        ),
    ]
